[tool.black]
line-length = 99

[tool.deptry]
requirements_txt = ["src/requirements.txt"]

[tool.coverage.run]
source = ["src"]

[tool.isort]
include_trailing_comma = true
line_length = 99
multi_line_output = 3
profile = "black"

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
install_types = true
non_interactive = true

[tool.pytest.ini_options]
addopts = "--cov --cov-append --cov-report=term-missing --cov-fail-under=30 -ra --show-capture=no --tb short"
python_files = ["*.py"]

[tool.ruff]
fix = false
ignore = ["ANN101", "B005", "BLE001", "D203", "D212", "D416", "PLR1711", "PLR2004", "S104", "T201"]
line-length = 99
select = ["A", "ANN", "ARG", "B", "BLE", "C4", "C90", "D", "E", "ERA", "F", "I", "ICN", "N", "PGH", "PLC", "PLE", "PLR", "PLW", "Q", "RET", "RUF", "S", "SIM", "T10", "T20", "TID", "UP", "W", "YTT"]

[tool.ruff.isort]
known-first-party = ["sms"]

[tool.ruff.per-file-ignores]
"tests/*" = ["ANN001", "ERA001", "S101"]
